### ISSUE TITLE
gotools needs to be updated for compatibility with the debugger in the newest version of Ghidra

### ISSUE THREAD

**Issue by cvar-ga** [felberj/gotools#8]
**Describe the bug**
The newest version of Ghidra, 10.0.1, operates with a debugger. Ghidra fails to update registers upon state change with the current version of gotools.

**Go version**: go1.16.6
**Target os**: Linux
**Ghidra version**: 10.0.1

**To Reproduce**
1. Unzip ghidra_9.1.2_PUBLIC_20200521_gotools.zip
2. Update version number to 10.0.1 in extension.properties
3. Re-zip
4. Move zip file to $GHIDRA_DIR/Extensions/Ghidra
5. Open Ghidra and install extension
6. Load a Go binary into debugger
7. Debug locally in GDB in VM
8. Set breakpoint anywhere
9. Click Resume
10. The error "Trouble updating registers on state change" appears in Debug Console

**Minimal source to reproduce**

```go
//none
```

**Expected behavior**
When I run the Go binary, I expect the register values to populate in the Registers tab, accessible when I click "Display Decompiler". Instead, no register updates, and each remain set to 0.

**Additional context**
N/A

**Comment by felberj** [comment]
I was able to reproduce this issue. But I can also reproduce the issue without the plugin. So I assume this is not an issue with the plugin but with Ghidra.
